arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-dir: lib/generated
output-class: S
nullable-getter: false
format: true
untranslated-messages-file: untranslated-messages.txt