name = "holis-app"
compatibility_date = "2023-01-01"
compatibility_flags = ["streams_enable_constructors"]

# Configuration for Cloudflare Pages
pages_build_output_dir = "build/web"

[env.production]

[env.preview]
name = "holis-app-preview"