// Mocks generated by Mockito 5.4.4 from annotations
// in nostrmo/test/util/notification_util_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:nostr_sdk/event.dart' as _i7;
import 'package:nostr_sdk/nip02/contact_list.dart' as _i8;
import 'package:nostr_sdk/nostr.dart' as _i4;
import 'package:nostr_sdk/relay/relay.dart' as _i3;
import 'package:nostr_sdk/signer/nostr_signer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNostrSigner_0 extends _i1.SmartFake implements _i2.NostrSigner {
  _FakeNostrSigner_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRelay_1 extends _i1.SmartFake implements _i3.Relay {
  _FakeRelay_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Nostr].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostr extends _i1.Mock implements _i4.Nostr {
  MockNostr() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NostrSigner get nostrSigner => (super.noSuchMethod(
        Invocation.getter(#nostrSigner),
        returnValue: _FakeNostrSigner_0(
          this,
          Invocation.getter(#nostrSigner),
        ),
      ) as _i2.NostrSigner);

  @override
  set nostrSigner(_i2.NostrSigner? _nostrSigner) => super.noSuchMethod(
        Invocation.setter(
          #nostrSigner,
          _nostrSigner,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onNotice(
          dynamic Function(
            String,
            String,
          )? _onNotice) =>
      super.noSuchMethod(
        Invocation.setter(
          #onNotice,
          _onNotice,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Relay Function(String) get tempRelayGener => (super.noSuchMethod(
        Invocation.getter(#tempRelayGener),
        returnValue: (String __p0) => _FakeRelay_1(
          this,
          Invocation.getter(#tempRelayGener),
        ),
      ) as _i3.Relay Function(String));

  @override
  set tempRelayGener(_i3.Relay Function(String)? _tempRelayGener) =>
      super.noSuchMethod(
        Invocation.setter(
          #tempRelayGener,
          _tempRelayGener,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get publicKey => (super.noSuchMethod(
        Invocation.getter(#publicKey),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#publicKey),
        ),
      ) as String);

  @override
  _i6.Future<_i7.Event?> sendLike(
    String? id, {
    String? pubkey,
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendLike,
          [id],
          {
            #pubkey: pubkey,
            #content: content,
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
          },
        ),
        returnValue: _i6.Future<_i7.Event?>.value(),
      ) as _i6.Future<_i7.Event?>);

  @override
  _i6.Future<_i7.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [eventId],
          {
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
          },
        ),
        returnValue: _i6.Future<_i7.Event?>.value(),
      ) as _i6.Future<_i7.Event?>);

  @override
  _i6.Future<_i7.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvents,
          [eventIds],
          {
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
          },
        ),
        returnValue: _i6.Future<_i7.Event?>.value(),
      ) as _i6.Future<_i7.Event?>);

  @override
  _i6.Future<_i7.Event?> sendRepost(
    String? id, {
    String? relayAddr,
    String? content = r'',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRepost,
          [id],
          {
            #relayAddr: relayAddr,
            #content: content,
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
          },
        ),
        returnValue: _i6.Future<_i7.Event?>.value(),
      ) as _i6.Future<_i7.Event?>);

  @override
  _i6.Future<_i7.Event?> sendContactList(
    _i8.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendContactList,
          [
            contacts,
            content,
          ],
          {
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
          },
        ),
        returnValue: _i6.Future<_i7.Event?>.value(),
      ) as _i6.Future<_i7.Event?>);

  @override
  _i6.Future<_i7.Event?> sendEvent(
    _i7.Event? event, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEvent,
          [event],
          {
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
          },
        ),
        returnValue: _i6.Future<_i7.Event?>.value(),
      ) as _i6.Future<_i7.Event?>);

  @override
  void checkEventSign(_i7.Event? event) => super.noSuchMethod(
        Invocation.method(
          #checkEventSign,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> signEvent(_i7.Event? event) => (super.noSuchMethod(
        Invocation.method(
          #signEvent,
          [event],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i7.Event? broadcase(
    _i7.Event? event, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #broadcase,
        [event],
        {
          #tempRelays: tempRelays,
          #targetRelays: targetRelays,
        },
      )) as _i7.Event?);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addInitQuery(
    List<Map<String, dynamic>>? filters,
    dynamic Function(_i7.Event)? onEvent, {
    String? id,
    Function? onComplete,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addInitQuery,
          [
            filters,
            onEvent,
          ],
          {
            #id: id,
            #onComplete: onComplete,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool tempRelayHasSubscription(String? relayAddr) => (super.noSuchMethod(
        Invocation.method(
          #tempRelayHasSubscription,
          [relayAddr],
        ),
        returnValue: false,
      ) as bool);

  @override
  String subscribe(
    List<Map<String, dynamic>>? filters,
    dynamic Function(_i7.Event)? onEvent, {
    String? id,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [
      1,
      2,
      3,
      4,
    ],
    bool? sendAfterAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [
            filters,
            onEvent,
          ],
          {
            #id: id,
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
            #relayTypes: relayTypes,
            #sendAfterAuth: sendAfterAuth,
          },
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #subscribe,
            [
              filters,
              onEvent,
            ],
            {
              #id: id,
              #tempRelays: tempRelays,
              #targetRelays: targetRelays,
              #relayTypes: relayTypes,
              #sendAfterAuth: sendAfterAuth,
            },
          ),
        ),
      ) as String);

  @override
  void unsubscribe(String? id) => super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i7.Event>> queryEvents(
    List<Map<String, dynamic>>? filters, {
    String? id,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [
      1,
      2,
      3,
      4,
    ],
    bool? sendAfterAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryEvents,
          [filters],
          {
            #id: id,
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
            #relayTypes: relayTypes,
            #sendAfterAuth: sendAfterAuth,
          },
        ),
        returnValue: _i6.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i6.Future<List<_i7.Event>>);

  @override
  String query(
    List<Map<String, dynamic>>? filters,
    dynamic Function(_i7.Event)? onEvent, {
    String? id,
    Function? onComplete,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [
      1,
      2,
      3,
      4,
    ],
    bool? sendAfterAuth = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [
            filters,
            onEvent,
          ],
          {
            #id: id,
            #onComplete: onComplete,
            #tempRelays: tempRelays,
            #targetRelays: targetRelays,
            #relayTypes: relayTypes,
            #sendAfterAuth: sendAfterAuth,
          },
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #query,
            [
              filters,
              onEvent,
            ],
            {
              #id: id,
              #onComplete: onComplete,
              #tempRelays: tempRelays,
              #targetRelays: targetRelays,
              #relayTypes: relayTypes,
              #sendAfterAuth: sendAfterAuth,
            },
          ),
        ),
      ) as String);

  @override
  String queryByFilters(
    Map<String, List<Map<String, dynamic>>>? filtersMap,
    dynamic Function(_i7.Event)? onEvent, {
    String? id,
    Function? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryByFilters,
          [
            filtersMap,
            onEvent,
          ],
          {
            #id: id,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #queryByFilters,
            [
              filtersMap,
              onEvent,
            ],
            {
              #id: id,
              #onComplete: onComplete,
            },
          ),
        ),
      ) as String);

  @override
  _i6.Future<bool> addRelay(
    _i3.Relay? relay, {
    bool? autoSubscribe = false,
    bool? init = false,
    int? relayType = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relay],
          {
            #autoSubscribe: autoSubscribe,
            #init: init,
            #relayType: relayType,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void removeRelay(
    String? url, {
    int? relayType = 1,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [url],
          {#relayType: relayType},
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Relay> activeRelays() => (super.noSuchMethod(
        Invocation.method(
          #activeRelays,
          [],
        ),
        returnValue: <_i3.Relay>[],
      ) as List<_i3.Relay>);

  @override
  _i3.Relay? getRelay(String? url) => (super.noSuchMethod(Invocation.method(
        #getRelay,
        [url],
      )) as _i3.Relay?);

  @override
  _i3.Relay? getTempRelay(String? url) => (super.noSuchMethod(Invocation.method(
        #getTempRelay,
        [url],
      )) as _i3.Relay?);

  @override
  void reconnect() => super.noSuchMethod(
        Invocation.method(
          #reconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getExtralReadableRelays(
    List<String>? extraRelays,
    int? maxRelayNum,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExtralReadableRelays,
          [
            extraRelays,
            maxRelayNum,
          ],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void removeTempRelay(String? addr) => super.noSuchMethod(
        Invocation.method(
          #removeTempRelay,
          [addr],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool readable() => (super.noSuchMethod(
        Invocation.method(
          #readable,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool writable() => (super.noSuchMethod(
        Invocation.method(
          #writable,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isReadOnly() => (super.noSuchMethod(
        Invocation.method(
          #isReadOnly,
          [],
        ),
        returnValue: false,
      ) as bool);
}
