// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3q2i11KQse0HzamNtpa31YSY8Yj0ph6s',
    appId: '1:253744100535:web:63f37888fbafdf691ec932',
    messagingSenderId: '253744100535',
    projectId: 'plur-623b0',
    authDomain: 'plur-623b0.firebaseapp.com',
    storageBucket: 'plur-623b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOo-fesVd35J_9m87qxEdGw9HX5Rjm_7Y',
    appId: '1:253744100535:android:8aa513f9b9c1fc521ec932',
    messagingSenderId: '253744100535',
    projectId: 'plur-623b0',
    storageBucket: 'plur-623b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7MHCBmO11-uU157sFhSAJgOMvtVwyA0',
    appId: '1:253744100535:ios:9e6b010ddcb402b31ec932',
    messagingSenderId: '253744100535',
    projectId: 'plur-623b0',
    storageBucket: 'plur-623b0.firebasestorage.app',
    iosBundleId: 'app.verse.prototype.plur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr7MHCBmO11-uU157sFhSAJgOMvtVwyA0',
    appId: '1:253744100535:ios:9e6b010ddcb402b31ec932',
    messagingSenderId: '253744100535',
    projectId: 'plur-623b0',
    storageBucket: 'plur-623b0.firebasestorage.app',
    iosBundleId: 'app.verse.prototype.plur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3q2i11KQse0HzamNtpa31YSY8Yj0ph6s',
    appId: '1:253744100535:web:470cc71d60ed8d801ec932',
    messagingSenderId: '253744100535',
    projectId: 'plur-623b0',
    authDomain: 'plur-623b0.firebaseapp.com',
    storageBucket: 'plur-623b0.firebasestorage.app',
  );
}
