#!/bin/bash

# Script to fix the most common localization issues quickly

# Directory containing the code
PROJECT_DIR="/Users/rabble/code/verse/plur"
cd "$PROJECT_DIR" || exit 1

echo "Starting quick localization fixes..."

# Find and fix common patterns all at once using a big sed command file
cat > /tmp/sed_commands.txt << 'EOL'
s/S\.of(context)\.About/S.of(context).about/g
s/S\.of(context)\.Address/S.of(context).address/g
s/S\.of(context)\.Add/S.of(context).add/g
s/S\.of(context)\.Admin/S.of(context).admin/g
s/S\.of(context)\.Banner/S.of(context).banner/g
s/S\.of(context)\.Blocks/S.of(context).blocks/g
s/S\.of(context)\.Cache/S.of(context).cache/g
s/S\.of(context)\.Cancel/S.of(context).cancel/g
s/S\.of(context)\.Communities/S.of(context).communities/g
s/S\.of(context)\.Confirm/S.of(context).confirm/g
s/S\.of(context)\.Content/S.of(context).content/g
s/S\.of(context)\.Copy/S.of(context).copy/g
s/S\.of(context)\.Copy_success/S.of(context).copySuccess/g
s/S\.of(context)\.Custom/S.of(context).custom/g
s/S\.of(context)\.Data/S.of(context).data/g
s/S\.of(context)\.Delete/S.of(context).delete/g
s/S\.of(context)\.Development/S.of(context).development/g
s/S\.of(context)\.Dirtywords/S.of(context).dirtywords/g
s/S\.of(context)\.Donate/S.of(context).donate/g
s/S\.of(context)\.Done/S.of(context).done/g
s/S\.of(context)\.Download/S.of(context).download/g
s/S\.of(context)\.Edit/S.of(context).edit/g
s/S\.of(context)\.Filter/S.of(context).filter/g
s/S\.of(context)\.Followed/S.of(context).followed/g
s/S\.of(context)\.Following/S.of(context).following/g
s/S\.of(context)\.Forbid/S.of(context).forbid/g
s/S\.of(context)\.Global/S.of(context).global/g
s/S\.of(context)\.Group/S.of(context).group/g
s/S\.of(context)\.Groups/S.of(context).groups/g
s/S\.of(context)\.Hashtag/S.of(context).hashtag/g
s/S\.of(context)\.Hide/S.of(context).hide/g
s/S\.of(context)\.Image/S.of(context).image/g
s/S\.of(context)\.Image_save_success/S.of(context).imageSaveSuccess/g
s/S\.of(context)\.Input/S.of(context).input/g
s/S\.of(context)\.Invite/S.of(context).invite/g
s/S\.of(context)\.Language/S.of(context).language/g
s/S\.of(context)\.Leave/S.of(context).leave/g
s/S\.of(context)\.Media/S.of(context).media/g
s/S\.of(context)\.Members/S.of(context).members/g
s/S\.of(context)\.Mentions/S.of(context).mentions/g
s/S\.of(context)\.Menu/S.of(context).menu/g
s/S\.of(context)\.Method/S.of(context).method/g
s/S\.of(context)\.More/S.of(context).more/g
s/S\.of(context)\.Name/S.of(context).name/g
s/S\.of(context)\.Network/S.of(context).network/g
s/S\.of(context)\.Notes/S.of(context).notes/g
s/S\.of(context)\.Notices/S.of(context).notices/g
s/S\.of(context)\.Notify/S.of(context).notify/g
s/S\.of(context)\.No/S.of(context).no/g
s/S\.of(context)\.Optional/S.of(context).optional/g
s/S\.of(context)\.Picture/S.of(context).picture/g
s/S\.of(context)\.Posts/S.of(context).posts/g
s/S\.of(context)\.Private/S.of(context).private/g
s/S\.of(context)\.Public/S.of(context).public/g
s/S\.of(context)\.Read/S.of(context).read/g
s/S\.of(context)\.Recovery/S.of(context).recovery/g
s/S\.of(context)\.Relays/S.of(context).relays/g
s/S\.of(context)\.Relay/S.of(context).relay/g
s/S\.of(context)\.Request/S.of(context).request/g
s/S\.of(context)\.Search/S.of(context).search/g
s/S\.of(context)\.Send/S.of(context).send/g
s/S\.of(context)\.Settings/S.of(context).settings/g
s/S\.of(context)\.Submit/S.of(context).submit/g
s/S\.of(context)\.Timeline/S.of(context).timeline/g
s/S\.of(context)\.Topics/S.of(context).topics/g
s/S\.of(context)\.Translate/S.of(context).translate/g
s/S\.of(context)\.This_operation_cannot_be_undo/S.of(context).thisOperationCannotBeUndo/g
s/S\.of(context)\.Use_lightning_wallet_scan_and_send_sats/S.of(context).useLightningWalletScanAndSendSats/g
s/S\.of(context)\.Users/S.of(context).users/g
s/S\.of(context)\.Website/S.of(context).website/g
s/S\.of(context)\.Write/S.of(context).write/g
s/S\.of(context)\.Yes/S.of(context).yes/g
s/S\.of(context)\.No_Media_found/S.of(context).noMediaFound/g
s/S\.of(context)\.Add_photos_to_posts/S.of(context).addPhotosToYourPosts/g
s/S\.of(context)\.File_Size/S.of(context).fileSize/g
s/S\.of(context)\.Clear_All_Data/S.of(context).clearAllData/g
s/S\.of(context)\.Clear_Not_My_Data/S.of(context).clearNotMyData/g
s/S\.of(context)\.Data_Sync_Mode/S.of(context).dataSyncMode/g
s/S\.of(context)\.Data_Length/S.of(context).dataLength/g
s/S\.of(context)\.Backup_my_notes/S.of(context).backupMyNotes/g
s/S\.of(context)\.Import_notes/S.of(context).importNotes/g
s/S\.of(context)\.Url/S.of(context).url/g
s/S\.of(context)\.Owner/S.of(context).owner/g
s/S\.of(context)\.Contact/S.of(context).contact/g
s/S\.of(context)\.Soft/S.of(context).soft/g
s/S\.of(context)\.Version/S.of(context).version/g
s/S\.of(context)\.Relay_Info/S.of(context).relayInfo/g
s/S\.of(context)\.Invite_people_to_join/S.of(context).invitePeopleToJoin/g
s/S\.of(context)\.Share_invite_description/S.of(context).shareInviteDescription/g
s/S\.of(context)\.Input_can_not_be_null/S.of(context).inputCanNotBeNull/g
s/S\.of(context)\.Pubkey/S.of(context).pubkey/g
s/S\.of(context)\.not_found/S.of(context).notFound/g
s/S\.of(context)\.Wrong_Private_Key_format/S.of(context).wrongPrivateKeyFormat/g
s/S\.of(context)\.Login_fail/S.of(context).loginFail/g
s/S\.of(context)\.Please_input_search_content/S.of(context).pleaseInputSearchContent/g
s/S\.of(context)\.NIP07_getPublicKey/S.of(context).nip07GetPublicKey/g
s/S\.of(context)\.NIP07_getRelays/S.of(context).nip07GetRelays/g
s/S\.of(context)\.NIP07_encrypt/S.of(context).nip07Encrypt/g
s/S\.of(context)\.NIP07_decrypt/S.of(context).nip07Decrypt/g
s/S\.of(context)\.NIP07_signEvent/S.of(context).nip07SignEvent/g
s/S\.of(context)\.NIP07_lightning/S.of(context).nip07Lightning/g

s/localization\.About/localization.about/g
s/localization\.Address/localization.address/g
s/localization\.Add/localization.add/g
s/localization\.Admin/localization.admin/g
s/localization\.Banner/localization.banner/g
s/localization\.Blocks/localization.blocks/g
s/localization\.Cache/localization.cache/g
s/localization\.Cancel/localization.cancel/g
s/localization\.Communities/localization.communities/g
s/localization\.Confirm/localization.confirm/g
s/localization\.Content/localization.content/g
s/localization\.Copy/localization.copy/g
s/localization\.Copy_success/localization.copySuccess/g
s/localization\.Custom/localization.custom/g
s/localization\.Data/localization.data/g
s/localization\.Delete/localization.delete/g
s/localization\.Development/localization.development/g
s/localization\.Dirtywords/localization.dirtywords/g
s/localization\.Donate/localization.donate/g
s/localization\.Done/localization.done/g
s/localization\.Download/localization.download/g
s/localization\.Edit/localization.edit/g
s/localization\.Filter/localization.filter/g
s/localization\.Followed/localization.followed/g
s/localization\.Following/localization.following/g
s/localization\.Forbid/localization.forbid/g
s/localization\.Global/localization.global/g
s/localization\.Group/localization.group/g
s/localization\.Groups/localization.groups/g
s/localization\.Hashtag/localization.hashtag/g
s/localization\.Hide/localization.hide/g
s/localization\.Image/localization.image/g
s/localization\.Image_save_success/localization.imageSaveSuccess/g
s/localization\.Input/localization.input/g
s/localization\.Invite/localization.invite/g
s/localization\.Language/localization.language/g
s/localization\.Leave/localization.leave/g
s/localization\.Media/localization.media/g
s/localization\.Members/localization.members/g
s/localization\.Mentions/localization.mentions/g
s/localization\.Menu/localization.menu/g
s/localization\.Method/localization.method/g
s/localization\.More/localization.more/g
s/localization\.Name/localization.name/g
s/localization\.Network/localization.network/g
s/localization\.Notes/localization.notes/g
s/localization\.Notices/localization.notices/g
s/localization\.Notify/localization.notify/g
s/localization\.No/localization.no/g
s/localization\.Optional/localization.optional/g
s/localization\.Picture/localization.picture/g
s/localization\.Posts/localization.posts/g
s/localization\.Private/localization.private/g
s/localization\.Public/localization.public/g
s/localization\.Read/localization.read/g
s/localization\.Recovery/localization.recovery/g
s/localization\.Relays/localization.relays/g
s/localization\.Relay/localization.relay/g
s/localization\.Request/localization.request/g
s/localization\.Search/localization.search/g
s/localization\.Send/localization.send/g
s/localization\.Settings/localization.settings/g
s/localization\.Submit/localization.submit/g
s/localization\.Timeline/localization.timeline/g
s/localization\.Topics/localization.topics/g
s/localization\.Translate/localization.translate/g
s/localization\.This_operation_cannot_be_undo/localization.thisOperationCannotBeUndo/g
s/localization\.Use_lightning_wallet_scan_and_send_sats/localization.useLightningWalletScanAndSendSats/g
s/localization\.Users/localization.users/g
s/localization\.Website/localization.website/g
s/localization\.Write/localization.write/g
s/localization\.Yes/localization.yes/g
s/localization\.No_Media_found/localization.noMediaFound/g
s/localization\.Add_photos_to_posts/localization.addPhotosToYourPosts/g
s/localization\.File_Size/localization.fileSize/g
s/localization\.Clear_All_Data/localization.clearAllData/g
s/localization\.Clear_Not_My_Data/localization.clearNotMyData/g
s/localization\.Data_Sync_Mode/localization.dataSyncMode/g
s/localization\.Data_Length/localization.dataLength/g
s/localization\.Backup_my_notes/localization.backupMyNotes/g
s/localization\.Import_notes/localization.importNotes/g
s/localization\.Url/localization.url/g
s/localization\.Owner/localization.owner/g
s/localization\.Contact/localization.contact/g
s/localization\.Soft/localization.soft/g
s/localization\.Version/localization.version/g
s/localization\.Relay_Info/localization.relayInfo/g
s/localization\.Invite_people_to_join/localization.invitePeopleToJoin/g
s/localization\.Share_invite_description/localization.shareInviteDescription/g
s/localization\.Input_can_not_be_null/localization.inputCanNotBeNull/g
s/localization\.Pubkey/localization.pubkey/g
s/localization\.not_found/localization.notFound/g
s/localization\.Wrong_Private_Key_format/localization.wrongPrivateKeyFormat/g
s/localization\.Login_fail/localization.loginFail/g
s/localization\.Please_input_search_content/localization.pleaseInputSearchContent/g
s/localization\.NIP07_getPublicKey/localization.nip07GetPublicKey/g
s/localization\.NIP07_getRelays/localization.nip07GetRelays/g
s/localization\.NIP07_encrypt/localization.nip07Encrypt/g
s/localization\.NIP07_decrypt/localization.nip07Decrypt/g
s/localization\.NIP07_signEvent/localization.nip07SignEvent/g
s/localization\.NIP07_lightning/localization.nip07Lightning/g
EOL

# Apply all changes at once to all Dart files
echo "Applying all replacements at once..."
find "$PROJECT_DIR/lib" -name "*.dart" -print0 | xargs -0 sed -i '' -f /tmp/sed_commands.txt

echo "Completed quick localization fixes. Please run Flutter analyze to verify the changes."