name: Analyze Project

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  FLUTTER_VERSION: 3.24.5

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    name: Generate Lint Reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - ${{ github.head_ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          submodules: recursive

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Lint the project
        run: flutter analyze --no-fatal-infos --no-fatal-warnings --write=lints.txt

      - name: Upload lints artifact
        uses: actions/upload-artifact@v4
        with:
          name: lints-${{ matrix.branch }}.txt
          path: lints.txt

  examine-lint-changes:
    name: Examine Lint Changes
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Download main branch artifact
        uses: actions/download-artifact@v4
        with:
          name: lints-main.txt
          path: main-lints.txt

      - name: Download PR branch artifact
        uses: actions/download-artifact@v4
        with:
          name: lints-${{ github.head_ref }}.txt
          path: pr-lints.txt

      - name: Compare lint results
        run: |
          diff -u main-lints.txt pr-lints.txt | grep "^+" | grep -v "^+++" > lint-additions.txt || true
          if [ -s lint-additions.txt ]; then
            echo "Found new lint issues in PR branch:"
            echo "## Found new lint issues in PR branch:" >> $GITHUB_STEP_SUMMARY
            cat lint-additions.txt >> $GITHUB_STEP_SUMMARY
            cat lint-additions.txt
            echo -e "\033[0;31mError: No new linting errors may be merged with main.\033[0m"
            exit 1
          else
            echo -e "\033[0;32mNo new lint issues found in PR branch.\033[0m"
          fi

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: recursive

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ env.FLUTTER_VERSION }}
  #         channel: 'stable'
  #         cache: true
  #         cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Run Tests
  #       run: |
  #         mkdir -p test-results
  #         flutter test --no-fail-fast -r github --file-reporter github:test-results/flutter_test_results.txt

  #     - name: Upload test results artifact
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: test-results
  #         path: test-results/