name: Analyze Project

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  FLUTTER_VERSION: 3.24.5

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze
        run: |
          dart pub global activate flutter_analyze_reporter
          flutter_analyze_reporter --reporter github
        shell: bash

# TODO: Uncomment the below once linting is configured.
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: recursive

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{ env.FLUTTER_VERSION }}
  #         channel: 'stable'
  #         cache: true
  #         cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Run Tests
  #       run: |
  #         mkdir -p test-results
  #         flutter test --no-fail-fast -r github --file-reporter github:test-results/flutter_test_results.txt

  #     - name: Upload test results artifact
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: test-results
  #         path: test-results/