name: TestFlight Release Deployment
on:
  push:
    branches:
      - 'release/**'
      - 'testflight-cd' # TOOD: Remove this
  # Enable manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fastlane-deploy:
    runs-on: macOS-14
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: 'recursive'
      #- name: Setup Flutter
      #  uses: subosito/flutter-action@v2
      #  with:
      #    flutter-version-file: pubspec.yaml
      #    channel: 'stable'
      #- name: Install Flutter Dependencies
      #  run: flutter pub get
      #- name: Build Flutter .app
      #  run: flutter build ios --release --no-codesign
      - uses: nomasystems/action-xcode-select@v0.1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ Secrets.SSH_KEY }}
          known_hosts: ${{ Secrets.KNOWN_HOSTS }}
      - name: Fastlane build and deploy
        working-directory: ./ios
        run: |
          bundle install
          bundle exec fastlane print_version
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ Secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ Secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ Secrets.APP_STORE_CONNECT_API_KEY_ID }}
          MATCH_PASSWORD: ${{ Secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASS: ${{ Secrets.KEYCHAIN_PASS }}
          SENTRY_AUTH: ${{ Secrets.SENTRY_AUTH }}
          APP_SECRETS: ${{ Secrets.APP_SECRETS }}
          CI: true
