name: Unit Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  FLUTTER_VERSION: 3.29.0

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run and Summarize tests
        run: |
          mkdir -p test-results
          flutter test --no-fail-fast -r github --file-reporter github:test-results/flutter_test_results.txt
          echo "##Flutter Test Results" >> test-results/summarized_test_results.txt
          grep -o "[✅❌].*" test-results/flutter_test_results.txt >> test-results/summarized_test_results.txt

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        if: always()
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Flutter Test Results
          
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        if: always()
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: test-results/summarized_test_results.txt
          edit-mode: replace
          
      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/